export interface Doctor {
  id: string;
  name: string;
  specialty: string;
  rating: number;
  qualification: string;
  experience: string;
  image: string;
  about?: string;
  timings?: string;
  fees?: string;
}

export const doctors: Doctor[] = [
  {
    id: "ananya-sharma",
    name: "Dr. Ananya Sharma",
    specialty: "Cardiologist",
    rating: 4.8,
    qualification: "MBBS, MD (Cardiology)",
    experience: "12 Years Experience",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    about: "Dr. Ananya Sharma specializes in heart-related treatments, including hypertension management, angioplasty and preventive cardiac care.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹800",
  },
  {
    id: "rohan-mehta",
    name: "Dr. Rohan Mehta",
    specialty: "Orthopedic Surgeon",
    rating: 4.7,
    qualification: "MBBS, MS (Ortho)",
    experience: "9 Years Experience",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    about: "Dr. Rohan Mehta specializes in joint replacements, sports injuries and fracture management.",
    timings: "Mon-Sat, 9 AM - 4 PM",
    fees: "₹700",
  },
  {
    id: "priya-nair",
    name: "Dr. Priya Nair",
    specialty: "Pediatrician",
    rating: 4.9,
    qualification: "MBBS, MD (Pediatrics)",
    experience: "15 Years Experience",
    image: "https://images.unsplash.com/photo-1550831107-1553da8c8464?w=400&h=400&fit=crop",
    about: "Dr. Priya Nair has extensive experience in child healthcare, immunizations and newborn care.",
    timings: "Mon-Sat, 10 AM - 6 PM",
    fees: "₹600",
  },
  {
    id: "arjun-verma",
    name: "Dr. Arjun Verma",
    specialty: "Neurologist",
    rating: 4.6,
    qualification: "MBBS, DM (Neurology)",
    experience: "11 Years Experience",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop",
    about: "Dr. Arjun Verma specializes in treating disorders of the brain, spine and nervous system.",
    timings: "Mon-Fri, 11 AM - 5 PM",
    fees: "₹900",
  },
  {
    id: "kavita-rao",
    name: "Dr. Kavita Rao",
    specialty: "Dermatologist",
    rating: 4.7,
    qualification: "MBBS, MD (Dermatology)",
    experience: "8 Years Experience",
    image: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop",
    about: "Dr. Kavita Rao specializes in skin, hair and cosmetic dermatology treatments.",
    timings: "Tue-Sun, 10 AM - 4 PM",
    fees: "₹700",
  },
  {
    id: "sameer-khan",
    name: "Dr. Sameer Khan",
    specialty: "General Physician",
    rating: 4.8,
    qualification: "MBBS, MD (Medicine)",
    experience: "14 Years Experience",
    image: "https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=400&h=400&fit=crop",
    about: "Dr. Sameer Khan provides comprehensive care for general health issues, fevers and chronic conditions.",
    timings: "Mon-Sat, 9 AM - 7 PM",
    fees: "₹500",
  },
  {
    id: "neha-kapoor",
    name: "Dr. Neha Kapoor",
    specialty: "Gynecologist",
    rating: 4.8,
    qualification: "MBBS, MS (Gynecology)",
    experience: "10 Years Experience",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
    about: "Dr. Neha Kapoor specializes in women's health, pregnancy care and gynecological surgeries.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹800",
  },
  {
    id: "vikram-singh",
    name: "Dr. Vikram Singh",
    specialty: "ENT Specialist",
    rating: 4.5,
    qualification: "MBBS, MS (ENT)",
    experience: "7 Years Experience",
    image: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&h=400&fit=crop",
    about: "Dr. Vikram Singh treats ear, nose and throat conditions including sinus and hearing issues.",
    timings: "Mon-Sat, 9 AM - 3 PM",
    fees: "₹600",
  },
  {
    id: "ritu-malhotra",
    name: "Dr. Ritu Malhotra",
    specialty: "Psychiatrist",
    rating: 4.9,
    qualification: "MBBS, MD (Psychiatry)",
    experience: "13 Years Experience",
    image: "https://images.unsplash.com/photo-1643297654416-05795d62e39c?w=400&h=400&fit=crop",
    about: "Dr. Ritu Malhotra specializes in mental health, anxiety, depression and stress management.",
    timings: "Mon-Fri, 11 AM - 6 PM",
    fees: "₹1000",
  },
  {
    id: "karan-joshi",
    name: "Dr. Karan Joshi",
    specialty: "Dentist",
    rating: 4.6,
    qualification: "BDS, MDS (Orthodontics)",
    experience: "6 Years Experience",
    image: "https://images.unsplash.com/photo-1637059824899-a441006a6875?w=400&h=400&fit=crop",
    about: "Dr. Karan Joshi specializes in orthodontics, braces and dental cosmetic procedures.",
    timings: "Mon-Sat, 10 AM - 6 PM",
    fees: "₹500",
  },
  {
    id: "meera-iyer",
    name: "Dr. Meera Iyer",
    specialty: "Ophthalmologist",
    rating: 4.7,
    qualification: "MBBS, MS (Ophthalmology)",
    experience: "9 Years Experience",
    image: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop",
    about: "Dr. Meera Iyer specializes in eye care, cataract surgery and vision correction.",
    timings: "Mon-Sat, 9 AM - 4 PM",
    fees: "₹700",
  },
  {
    id: "aditya-bansal",
    name: "Dr. Aditya Bansal",
    specialty: "Urologist",
    rating: 4.6,
    qualification: "MBBS, MCh (Urology)",
    experience: "11 Years Experience",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    about: "Dr. Aditya Bansal specializes in urinary tract and kidney-related surgical treatments.",
    timings: "Mon-Fri, 10 AM - 5 PM",
    fees: "₹900",
  },
  {
    id: "rahul-khanna",
    name: "Dr. Rahul Khanna",
    specialty: "Pulmonologist",
    rating: 4.7,
    qualification: "MBBS, MD (Pulmonary Medicine)",
    experience: "10 Years Experience",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop",
    about: "Dr. Rahul Khanna specializes in lung disorders, asthma and respiratory conditions.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹800",
  },
  {
    id: "sneha-verma",
    name: "Dr. Sneha Verma",
    specialty: "Endocrinologist",
    rating: 4.8,
    qualification: "MBBS, MD (Endocrinology)",
    experience: "12 Years Experience",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    about: "Dr. Sneha Verma specializes in diabetes, thyroid and hormonal disorders.",
    timings: "Mon-Sat, 9 AM - 4 PM",
    fees: "₹800",
  },
  {
    id: "amit-malhotra",
    name: "Dr. Amit Malhotra",
    specialty: "Gastroenterologist",
    rating: 4.9,
    qualification: "MBBS, MD, DM (Gastroenterology)",
    experience: "14 Years Experience",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop",
    about: "Dr. Amit Malhotra specializes in digestive disorders, liver disease and endoscopy procedures.",
    timings: "Mon-Fri, 10 AM - 5 PM",
    fees: "₹1000",
  },
  {
    id: "pooja-sharma",
    name: "Dr. Pooja Sharma",
    specialty: "Oncologist",
    rating: 4.8,
    qualification: "MBBS, MD (Medical Oncology)",
    experience: "13 Years Experience",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    about: "Dr. Pooja Sharma specializes in cancer diagnosis, chemotherapy and treatment planning.",
    timings: "Mon-Fri, 10 AM - 4 PM",
    fees: "₹1200",
  },
  {
    id: "rajiv-kapoor",
    name: "Dr. Rajiv Kapoor",
    specialty: "Nephrologist",
    rating: 4.9,
    qualification: "MBBS, MD, DM (Nephrology)",
    experience: "16 Years Experience",
    image: "https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=400&h=400&fit=crop",
    about: "Dr. Rajiv Kapoor specializes in kidney disease, dialysis and hypertension management.",
    timings: "Mon-Sat, 9 AM - 4 PM",
    fees: "₹1000",
  },
  {
    id: "simran-kaur",
    name: "Dr. Simran Kaur",
    specialty: "Rheumatologist",
    rating: 4.7,
    qualification: "MBBS, MD (Rheumatology)",
    experience: "9 Years Experience",
    image: "https://images.unsplash.com/photo-1550831107-1553da8c8464?w=400&h=400&fit=crop",
    about: "Dr. Simran Kaur specializes in arthritis, autoimmune disorders and joint pain treatment.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹800",
  },
  {
    id: "nikhil-agarwal",
    name: "Dr. Nikhil Agarwal",
    specialty: "General Surgeon",
    rating: 4.6,
    qualification: "MBBS, MS (General Surgery)",
    experience: "11 Years Experience",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop",
    about: "Dr. Nikhil Agarwal specializes in general and laparoscopic surgical procedures.",
    timings: "Mon-Sat, 9 AM - 5 PM",
    fees: "₹700",
  },
  {
    id: "aisha-khan",
    name: "Dr. Aisha Khan",
    specialty: "Allergist",
    rating: 4.8,
    qualification: "MBBS, MD (Allergy & Immunology)",
    experience: "8 Years Experience",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
    about: "Dr. Aisha Khan specializes in allergies, asthma and immune-related disorders.",
    timings: "Mon-Sat, 10 AM - 4 PM",
    fees: "₹600",
  },
  {
    id: "manish-gupta",
    name: "Dr. Manish Gupta",
    specialty: "Plastic Surgeon",
    rating: 4.9,
    qualification: "MBBS, MS, MCh (Plastic Surgery)",
    experience: "15 Years Experience",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop",
    about: "Dr. Manish Gupta specializes in reconstructive and cosmetic plastic surgery.",
    timings: "Mon-Fri, 11 AM - 5 PM",
    fees: "₹1500",
  },
  {
    id: "shreya-nair",
    name: "Dr. Shreya Nair",
    specialty: "Radiologist",
    rating: 4.6,
    qualification: "MBBS, MD (Radiology)",
    experience: "7 Years Experience",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    about: "Dr. Shreya Nair specializes in diagnostic imaging including X-rays, MRI and CT scans.",
    timings: "Mon-Sat, 9 AM - 5 PM",
    fees: "₹700",
  },
  {
    id: "varun-sethi",
    name: "Dr. Varun Sethi",
    specialty: "Cardiac Surgeon",
    rating: 4.9,
    qualification: "MBBS, MS, MCh (Cardiothoracic Surgery)",
    experience: "17 Years Experience",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop",
    about: "Dr. Varun Sethi specializes in complex cardiac surgeries and bypass procedures.",
    timings: "Mon-Fri, 10 AM - 4 PM",
    fees: "₹1500",
  },
  {
    id: "isha-patel",
    name: "Dr. Isha Patel",
    specialty: "Physiotherapist",
    rating: 4.7,
    qualification: "BPT, MPT (Orthopedics)",
    experience: "6 Years Experience",
    image: "https://images.unsplash.com/photo-1643297654416-05795d62e39c?w=400&h=400&fit=crop",
    about: "Dr. Isha Patel specializes in physical rehabilitation and orthopedic recovery therapy.",
    timings: "Mon-Sat, 9 AM - 6 PM",
    fees: "₹500",
  },
  {
    id: "abhishek-roy",
    name: "Dr. Abhishek Roy",
    specialty: "Hematologist",
    rating: 4.8,
    qualification: "MBBS, MD, DM (Hematology)",
    experience: "12 Years Experience",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    about: "Dr. Abhishek Roy specializes in blood disorders including anemia and clotting issues.",
    timings: "Mon-Fri, 10 AM - 5 PM",
    fees: "₹900",
  },
  {
    id: "tanya-mehra",
    name: "Dr. Tanya Mehra",
    specialty: "Cosmetologist",
    rating: 4.7,
    qualification: "MBBS, MD (Cosmetology)",
    experience: "8 Years Experience",
    image: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop",
    about: "Dr. Tanya Mehra specializes in skin rejuvenation and cosmetic aesthetic treatments.",
    timings: "Tue-Sun, 10 AM - 5 PM",
    fees: "₹800",
  },
  {
    id: "saurabh-jain",
    name: "Dr. Saurabh Jain",
    specialty: "Infectious Disease Specialist",
    rating: 4.8,
    qualification: "MBBS, MD (Infectious Diseases)",
    experience: "10 Years Experience",
    image: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&h=400&fit=crop",
    about: "Dr. Saurabh Jain specializes in diagnosing and treating infectious and tropical diseases.",
    timings: "Mon-Sat, 9 AM - 4 PM",
    fees: "₹700",
  },
  {
    id: "nandini-rao",
    name: "Dr. Nandini Rao",
    specialty: "Nutritionist",
    rating: 4.6,
    qualification: "MBBS, MSc (Clinical Nutrition)",
    experience: "7 Years Experience",
    image: "https://images.unsplash.com/photo-1550831107-1553da8c8464?w=400&h=400&fit=crop",
    about: "Dr. Nandini Rao specializes in diet planning and nutrition for chronic disease management.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹500",
  },
  {
    id: "mohit-sharma",
    name: "Dr. Mohit Sharma",
    specialty: "Emergency Medicine Specialist",
    rating: 4.8,
    qualification: "MBBS, MD (Emergency Medicine)",
    experience: "9 Years Experience",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop",
    about: "Dr. Mohit Sharma specializes in emergency and critical care medicine.",
    timings: "24x7 On Call",
    fees: "₹800",
  },
  {
    id: "riya-kapoor",
    name: "Dr. Riya Kapoor",
    specialty: "Clinical Psychologist",
    rating: 4.9,
    qualification: "MA, MPhil (Clinical Psychology)",
    experience: "8 Years Experience",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
    about: "Dr. Riya Kapoor specializes in counseling, therapy and behavioral health.",
    timings: "Mon-Sat, 11 AM - 6 PM",
    fees: "₹900",
  },
  {
    id: "yashvardhan-singh",
    name: "Dr. Yashvardhan Singh",
    specialty: "Cardiothoracic Surgeon",
    rating: 4.8,
    qualification: "MBBS, MS, MCh (Cardiothoracic Surgery)",
    experience: "14 Years Experience",
    image: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=400&h=400&fit=crop",
    about: "Dr. Yashvardhan Singh specializes in heart and chest surgical procedures.",
    timings: "Mon-Fri, 10 AM - 4 PM",
    fees: "₹1500",
  },
  {
    id: "anjali-deshmukh",
    name: "Dr. Anjali Deshmukh",
    specialty: "Obstetrician & Gynecologist",
    rating: 4.9,
    qualification: "MBBS, MD (Obstetrics & Gynecology)",
    experience: "11 Years Experience",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&h=400&fit=crop",
    about: "Dr. Anjali Deshmukh specializes in pregnancy care, delivery and women's reproductive health.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹900",
  },

  // 3 naye doctors
  {
    id: "harsh-vardhan",
    name: "Dr. Harsh Vardhan",
    specialty: "Neurosurgeon",
    rating: 4.9,
    qualification: "MBBS, MS, MCh (Neurosurgery)",
    experience: "16 Years Experience",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    about: "Dr. Harsh Vardhan specializes in brain and spine surgical procedures.",
    timings: "Mon-Fri, 10 AM - 4 PM",
    fees: "₹1800",
  },
  {
    id: "kritika-saxena",
    name: "Dr. Kritika Saxena",
    specialty: "Pediatric Surgeon",
    rating: 4.7,
    qualification: "MBBS, MS, MCh (Pediatric Surgery)",
    experience: "10 Years Experience",
    image: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop",
    about: "Dr. Kritika Saxena specializes in surgical treatment of congenital and pediatric conditions.",
    timings: "Mon-Sat, 10 AM - 5 PM",
    fees: "₹1000",
  },
  {
    id: "farhan-ansari",
    name: "Dr. Farhan Ansari",
    specialty: "Vascular Surgeon",
    rating: 4.8,
    qualification: "MBBS, MS, MCh (Vascular Surgery)",
    experience: "13 Years Experience",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop",
    about: "Dr. Farhan Ansari specializes in treating blood vessel disorders and varicose veins.",
    timings: "Mon-Fri, 10 AM - 4 PM",
    fees: "₹1200",
  },
];